site_name: City.Chain.Explorer
site_description: City Chain Explorer API Documentation
site_author: Clint Mourlevat
repo_url: https://github.com/CityChainFoundation/city-explorer.git
theme: readthedocs
