site_name: Stratis.Guru Documentation
site_description: Strati.Guru API Documentation
site_author: Clint Mourlevat
repo_url: https://github.com/clintnetwork/stratis-guru-v2.git
google_analytics: ["UA-111742056-1", "stratis.guru"]
theme: readthedocs
